# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/parallels/Desktop/aa-project

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/parallels/Desktop/aa-project

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/parallels/Desktop/aa-project/CMakeFiles /home/parallels/Desktop/aa-project/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/parallels/Desktop/aa-project/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named graph_lib

# Build rule for target.
graph_lib: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graph_lib
.PHONY : graph_lib

# fast build rule for target.
graph_lib/fast:
	$(MAKE) -f CMakeFiles/graph_lib.dir/build.make CMakeFiles/graph_lib.dir/build
.PHONY : graph_lib/fast

#=============================================================================
# Target rules for targets named graph_parser

# Build rule for target.
graph_parser: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 graph_parser
.PHONY : graph_parser

# fast build rule for target.
graph_parser/fast:
	$(MAKE) -f CMakeFiles/graph_parser.dir/build.make CMakeFiles/graph_parser.dir/build
.PHONY : graph_parser/fast

#=============================================================================
# Target rules for targets named we_parallel

# Build rule for target.
we_parallel: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 we_parallel
.PHONY : we_parallel

# fast build rule for target.
we_parallel/fast:
	$(MAKE) -f CMakeFiles/we_parallel.dir/build.make CMakeFiles/we_parallel.dir/build
.PHONY : we_parallel/fast

#=============================================================================
# Target rules for targets named we_serial

# Build rule for target.
we_serial: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 we_serial
.PHONY : we_serial

# fast build rule for target.
we_serial/fast:
	$(MAKE) -f CMakeFiles/we_serial.dir/build.make CMakeFiles/we_serial.dir/build
.PHONY : we_serial/fast

Graph.o: Graph.cpp.o
.PHONY : Graph.o

# target to build an object file
Graph.cpp.o:
	$(MAKE) -f CMakeFiles/graph_lib.dir/build.make CMakeFiles/graph_lib.dir/Graph.cpp.o
.PHONY : Graph.cpp.o

Graph.i: Graph.cpp.i
.PHONY : Graph.i

# target to preprocess a source file
Graph.cpp.i:
	$(MAKE) -f CMakeFiles/graph_lib.dir/build.make CMakeFiles/graph_lib.dir/Graph.cpp.i
.PHONY : Graph.cpp.i

Graph.s: Graph.cpp.s
.PHONY : Graph.s

# target to generate assembly for a file
Graph.cpp.s:
	$(MAKE) -f CMakeFiles/graph_lib.dir/build.make CMakeFiles/graph_lib.dir/Graph.cpp.s
.PHONY : Graph.cpp.s

graph_parser.o: graph_parser.cpp.o
.PHONY : graph_parser.o

# target to build an object file
graph_parser.cpp.o:
	$(MAKE) -f CMakeFiles/graph_parser.dir/build.make CMakeFiles/graph_parser.dir/graph_parser.cpp.o
.PHONY : graph_parser.cpp.o

graph_parser.i: graph_parser.cpp.i
.PHONY : graph_parser.i

# target to preprocess a source file
graph_parser.cpp.i:
	$(MAKE) -f CMakeFiles/graph_parser.dir/build.make CMakeFiles/graph_parser.dir/graph_parser.cpp.i
.PHONY : graph_parser.cpp.i

graph_parser.s: graph_parser.cpp.s
.PHONY : graph_parser.s

# target to generate assembly for a file
graph_parser.cpp.s:
	$(MAKE) -f CMakeFiles/graph_parser.dir/build.make CMakeFiles/graph_parser.dir/graph_parser.cpp.s
.PHONY : graph_parser.cpp.s

work_efficient_parallel.o: work_efficient_parallel.cpp.o
.PHONY : work_efficient_parallel.o

# target to build an object file
work_efficient_parallel.cpp.o:
	$(MAKE) -f CMakeFiles/we_parallel.dir/build.make CMakeFiles/we_parallel.dir/work_efficient_parallel.cpp.o
.PHONY : work_efficient_parallel.cpp.o

work_efficient_parallel.i: work_efficient_parallel.cpp.i
.PHONY : work_efficient_parallel.i

# target to preprocess a source file
work_efficient_parallel.cpp.i:
	$(MAKE) -f CMakeFiles/we_parallel.dir/build.make CMakeFiles/we_parallel.dir/work_efficient_parallel.cpp.i
.PHONY : work_efficient_parallel.cpp.i

work_efficient_parallel.s: work_efficient_parallel.cpp.s
.PHONY : work_efficient_parallel.s

# target to generate assembly for a file
work_efficient_parallel.cpp.s:
	$(MAKE) -f CMakeFiles/we_parallel.dir/build.make CMakeFiles/we_parallel.dir/work_efficient_parallel.cpp.s
.PHONY : work_efficient_parallel.cpp.s

work_efficient_sequential.o: work_efficient_sequential.cpp.o
.PHONY : work_efficient_sequential.o

# target to build an object file
work_efficient_sequential.cpp.o:
	$(MAKE) -f CMakeFiles/we_serial.dir/build.make CMakeFiles/we_serial.dir/work_efficient_sequential.cpp.o
.PHONY : work_efficient_sequential.cpp.o

work_efficient_sequential.i: work_efficient_sequential.cpp.i
.PHONY : work_efficient_sequential.i

# target to preprocess a source file
work_efficient_sequential.cpp.i:
	$(MAKE) -f CMakeFiles/we_serial.dir/build.make CMakeFiles/we_serial.dir/work_efficient_sequential.cpp.i
.PHONY : work_efficient_sequential.cpp.i

work_efficient_sequential.s: work_efficient_sequential.cpp.s
.PHONY : work_efficient_sequential.s

# target to generate assembly for a file
work_efficient_sequential.cpp.s:
	$(MAKE) -f CMakeFiles/we_serial.dir/build.make CMakeFiles/we_serial.dir/work_efficient_sequential.cpp.s
.PHONY : work_efficient_sequential.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... graph_lib"
	@echo "... graph_parser"
	@echo "... rebuild_cache"
	@echo "... we_parallel"
	@echo "... we_serial"
	@echo "... Graph.o"
	@echo "... Graph.i"
	@echo "... Graph.s"
	@echo "... graph_parser.o"
	@echo "... graph_parser.i"
	@echo "... graph_parser.s"
	@echo "... work_efficient_parallel.o"
	@echo "... work_efficient_parallel.i"
	@echo "... work_efficient_parallel.s"
	@echo "... work_efficient_sequential.o"
	@echo "... work_efficient_sequential.i"
	@echo "... work_efficient_sequential.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

